server:
  port: 8000

spring:
  spring:
    security:
      oauth2:
        client:
          registration:
            google:
              client-id:

  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#    url: jdbc:mysql://localhost:3306/restaurant
#    username: root
#    password: q1w2e3r4
